### ISSUE TITLE
ModuleNotFoundError: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by TheDukeSr** [boralyl/kodi-recently-added#1]
Running HASS version 0.115.3 in virtualenv on Raspberry.
After installing integration and running Configuration validation in HASS, this error came up:

**ModuleNotFoundError: No module named 'typing_extensions'**

Solution:
In putty go to correct user env.
`sudo -u homeassistant -H -s`
Activate env.
`source /srv/homeassistant/bin/activate`
Install missing extension:
`pip3 install typing_extensions`

**Comment by boralyl** [comment]
Thanks for reporting!  Fixed in 1285f30
