### ISSUE TITLE
Missing  version key in the manifest file.

### ISSUE THREAD

**Issue by TheDukeSr** [boralyl/kodi-recently-added#10]
_Warning in Log:_
No 'version' key in the manifest file for custom integration 'kodi_recently_added'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'kodi_recently_added'

Hass Version: core-2021.4.3

**Comment by boralyl** [comment]
Thanks for the reminder!  I added the version key weeks ago but never published a new release.  The latest version will get rid of the warning message.
