### ISSUE TITLE
Not in HACS & cant add it as custom

### ISSUE THREAD

**Issue by codeclinic** [boralyl/kodi-recently-added#2]
I've tried adding this to HACS as a custom repo but it refuses, saying that the format of the repo is not compatible.

**Comment by boralyl** [comment]
Thanks for reporting, I haven't tried adding this as a custom repo in HACS, I'll give it a try today.

**Comment by boralyl** [comment]
This appears to work for me, did you choose `integration` as the category?

![image](https://user-images.githubusercontent.com/109865/94345428-8c4c8580-ffda-11ea-968e-702ecf00d586.png)

**Comment by codeclinic** [comment]
I thought I had tried that and lovelace as an option. But, I just tried it now and it worked.

Sorry for wasting your time.
