### ISSUE TITLE
won't work anymore

### ISSUE THREAD

**Issue by compujunk** [boralyl/kodi-recently-added#3]
I reinstalled kodi-recently-added (the version that is for HA 0.115 and above)
and i put the sensors in my configuration.yaml but they don't show up.
In my log file I see the following:

Logger: homeassistant.components.sensor
Source: custom_components/kodi_recently_added/sensor.py:48
Integration: Sensor (documentation, issues)
First occurred: 10:53:18 (1 occurrences)
Last logged: 10:53:18

Error while setting up kodi_recently_added platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/kodi_recently_added/sensor.py", line 48, in async_setup_platform
    data = hass.data[KODI_DOMAIN][config_entry.entry_id]
KeyError: '5a5c9f95010011eb8d4ad5a5ae663505'

**Comment by boralyl** [comment]
What I would suggest is completely removing the `kodi` integration via the integrations page and re-adding it.  Afterwards restart HA and let me know if you are still seeing the error.

**Comment by compujunk** [comment]
Done, I have removed kodi via the integrations page and re-adding it.
after the restart i get the same error:

Logger: homeassistant.components.sensor
Source: custom_components/kodi_recently_added/sensor.py:48
Integration: Sensor (documentation, issues)
First occurred: 0:50:04 (1 occurrences)
Last logged: 0:50:04

Error while setting up kodi_recently_added platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/kodi_recently_added/sensor.py", line 48, in async_setup_platform
    data = hass.data[KODI_DOMAIN][config_entry.entry_id]
KeyError: '5a5c9f95010011eb8d4ad5a5ae663505'

**Comment by boralyl** [comment]
Are you comfortable enough with your setup to be able to replace the `sensor.py` mentioned in the error with a custom version that could help debug this issue?  My current guess is that there are multiple config entries for the host you have used and for some reason the old one is being found first that no longer has data in the kodi domain within hass.data.

If you are comfortable doing this I can provide an updated version that adds some additional logging that might help figure out how to resolve this issue.

**Comment by boralyl** [comment]
If you are able to copy this file: https://gist.githubusercontent.com/boralyl/383dbedf943d185a70b99ca9ea35c050/raw/512c52b9203ba74aadfc621d0afb9298ccaa2e8a/sensor.py to `/config/custom_components/kodi_recently_added/sensor.py` and restart HA you should see some new warning logs that will provide some more insight into your issue.

If you could post each warning, there will be at least 2 but possibly more that will help out.  Please make sure that you scrub the pasted logs of any sensitive information like passwords/usernames.  You can just replace those values with an empty string.

**Comment by compujunk** [comment]
I get one error:

Logger: homeassistant.components.sensor
Source: custom_components/kodi_recently_added/sensor.py:25
Integration: Sensor (documentation, issues)
First occurred: 20:47:39 (1 occurrences)
Last logged: 20:47:39

Error while setting up kodi_recently_added platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/kodi_recently_added/sensor.py", line 35, in async_setup_platform
    config_entry = find_matching_config_entry_for_host(hass, host)
  File "/config/custom_components/kodi_recently_added/sensor.py", line 25, in find_matching_config_entry_for_host
    if entry.data[CONF_HOST] == host:
KeyError: 'host'

**Comment by compujunk** [comment]
I also added a second kodi and then I get another error:

Logger: homeassistant.components.sensor
Source: custom_components/kodi_recently_added/sensor.py:51
Integration: Sensor (documentation, issues)
First occurred: 21:00:37 (1 occurrences)
Last logged: 21:00:37

Error while setting up kodi_recently_added platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/kodi_recently_added/sensor.py", line 51, in async_setup_platform
    data = hass.data[KODI_DOMAIN][config_entry.entry_id]
KeyError: '5a5c9f95010011eb8d4ad5a5ae663505'


maybe also worth mentioning, I use MySQL as a common database for all my kodis in the house.
Previously this was no problem and it just worked.

**Comment by compujunk** [comment]
Oh, I saw 2 still there:

1e
====================================

Logger: custom_components.kodi_recently_added.sensor
Source: custom_components/kodi_recently_added/sensor.py:50
Integration: Kodi Recently Added Media (documentation, issues)
First occurred: 21:00:36 (5 occurrences)
Last logged: 21:00:36

kodi domain config entry ids: ['3f2e1289069511ebb60f0b8767d165ca', 'd989d614069311eb89d82358eba11511']


2e
========================

Logger: custom_components.kodi_recently_added.sensor
Source: custom_components/kodi_recently_added/sensor.py:49
Integration: Kodi Recently Added Media (documentation, issues)
First occurred: 21:00:36 (5 occurrences)
Last logged: 21:00:36

config_entry: {'entry_id': '5a5c9f95010011eb8d4ad5a5ae663505', 'version': 1, 'domain': 'kodi', 'title': 'Ignored', 'data': {'host': '192.168.1.1', 'port': 8080, 'name': 'donald-2'}, 'options': {}, 'system_options': {'disable_new_entities': False}, 'source': 'ignore', 'connection_class': 'local_poll', 'unique_id': '936f3519-6be0-4bba-9019-084899a6628d'}
config_entry: {'entry_id': '5c300c0d010011eba0102bcd7677b8ab', 'version': 1, 'domain': 'kodi', 'title': 'Ignored', 'data': {}, 'options': {}, 'system_options': {'disable_new_entities': False}, 'source': 'ignore', 'connection_class': 'local_poll', 'unique_id': 'dff98f68-94ab-4611-a40a-b2066b6b1764'}
config_entry: {'entry_id': '694e851a010011eb8dc5c9ad9ea08da8', 'version': 1, 'domain': 'kodi', 'title': 'Ignored', 'data': {}, 'options': {}, 'system_options': {'disable_new_entities': False}, 'source': 'ignore', 'connection_class': 'local_poll', 'unique_id': '25470886-d7b8-4f48-8280-76baad9697be'}
config_entry: {'entry_id': 'd989d614069311eb89d82358eba11511', 'version': 1, 'domain': 'kodi', 'title': '192.168.0.200', 'data': {'name': None, 'host': '192.168.0.200', 'port': 8080, 'ws_port': 9090, 'username': '', 'password': '', 'ssl': False, 'timeout': 5}, 'options': {}, 'system_options': {'disable_new_entities': False}, 'source': 'user', 'connection_class': 'local_poll', 'unique_id': None}
config_entry: {'entry_id': '3f2e1289069511ebb60f0b8767d165ca', 'version': 1, 'domain': 'kodi', 'title': '192.168.1.1', 'data': {'name': None, 'host': '192.168.1.1', 'port': 8080, 'ws_port': 9090, 'username': '', 'password': '', 'ssl': False, 'timeout': 5}, 'options': {}, 'system_options': {'disable_new_entities': False}, 'source': 'user', 'connection_class': 'local_poll', 'unique_id': None}

**Comment by boralyl** [comment]
Thanks for posting, I think I see what's going on.  It appears to be including what look like ignored entries.  I'll have a fix you can try out later tonight.

**Comment by boralyl** [comment]
Would you mind trying replacing your sensor.py with the latest version in master? https://raw.githubusercontent.com/boralyl/kodi-recently-added/master/custom_components/kodi_recently_added/sensor.py

Let me know if this fixes your issue and I can create a new release after adding some tests.

**Comment by compujunk** [comment]
i still get an error:

Logger: homeassistant.components.sensor
Source: custom_components/kodi_recently_added/sensor.py:26
Integration: Sensor (documentation, issues)
First occurred: 11:17:07 (1 occurrences)
Last logged: 11:17:07

Error while setting up kodi_recently_added platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/kodi_recently_added/sensor.py", line 36, in async_setup_platform
    config_entry = find_matching_config_entry_for_host(hass, host)
  File "/config/custom_components/kodi_recently_added/sensor.py", line 26, in find_matching_config_entry_for_host
    if entry.data[CONF_HOST] == host and entry.source != "ignore":
KeyError: 'host'

**Comment by boralyl** [comment]
Whoops, I missed the other error you had posted.  I pushed a fix for that to master.  I think that should resolve your last issue.

**Comment by compujunk** [comment]
Yes it works again, thanks.
But what does this mean when there is another update of Kodi Recently Added Media. is the error in it again or do you process the solution in the new version?

**Comment by boralyl** [comment]
I will roll this into the next release, so the next time you see an update in HACS it will include this fix.
