### ISSUE TITLE
[Feature Request] Consider changing the mdi:arrow-down-bold to mdi:eye-off

### ISSUE THREAD

**Issue by 4841penoyer** [boralyl/kodi-recently-added#5]
Consider changing the mdi:arrow-down-bold to mdi:eye-off

This would bring it in line with the Plex component and in my opinion is more descriptive of what the icon actually means.  

Low priority request from me, as I'm requesting that upcoming-media-card have a feature to not display the icon, because in my use case everything will be un-watched.

**Comment by 4841penoyer** [comment]
Even lower request now that I reread upcoming-media-card documentation and noticed I can already hide the flag

**Comment by boralyl** [comment]
Thanks for reporting, I agree the `mdi:eye-off` icon makes more sense in this case.  I've updated this and it will be fixed in the next release.
