### ISSUE TITLE
zeronconf and discovery and sonof not available if thst is installed  on HA 118.4  

### ISSUE THREAD

**Issue by aladin2000** [boralyl/kodi-recently-added#7]
**Describe the bug**

Wen installed , the integrated kodi-recently-added component 
make other dependancies not availabel anymore
zeroconf
sonoff
discovery
As soon as I delete the components, then the oters work again 

**To Reproduce**
1. Install custom_commponent to corect directory kodi_media_added
2. reboot HA
3. zeroconf  sonoff  discovery  are not working
4  see 

Logger: homeassistant.setup
Source: setup.py:118
First occurred: 18:40:42 (1 occurrences)
Last logged: 18:40:42
Unable to set up dependencies of sonoff. Setup failed for dependencies: zeroconf 

Logger: homeassistant.setup
Source: components/zeroconf/__init__.py:90
First occurred: 18:40:38 (2 occurrences)
Last logged: 18:40:46

    Error during setup of component zeroconf
    Error during setup of component discovery

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/src/homeassistant/homeassistant/components/zeroconf/__init__.py", line 142, in async_setup
    zeroconf = hass.data[DOMAIN] = await _async_get_instance(hass, **zc_args)
  File "/usr/src/homeassistant/homeassistant/components/zeroconf/__init__.py", line 90, in _async_get_instance
    zeroconf = await hass.async_add_executor_job(partial(HaZeroconf, **zcargs))
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2394, in __init__
    self._listen_socket, self._respond_sockets = create_sockets(
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2319, in create_sockets
    respond_socket = add_multicast_member(cast(socket.socket, listen_socket), i, apple_p2p=apple_p2p)
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2264, in add_multicast_member
    listen_socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value)
OSError: [Errno 105] No buffer space available

**Expected behavior**

**Screenshots**

**Home Assistant and Custom Component versions (please complete the following information):**
Home Assistant version: 118.4
kodi-recently-added component version: last one

**Additional context**

**Comment by boralyl** [comment]
Thanks for reporting!  How are you running on HA and on what type of hardware?  The logs don't mention this component so I'm not sure there is anything I can change on the custom component side to resolve the setup errors.  This looks like an OS level error based on the last line in the log: `OSError: [Errno 105] No buffer space available`

I must admit I'm not familiar with this error or multicasting in general.  Perhaps this is helpful?
https://blog.mphomphego.co.za/blog/2017/06/28/why-am-i-getting-errno105-no-buffer-space-available-when-subscribing-to-multicast-addresses.html

**Comment by aladin2000** [comment]
thanks a lot. I try with your input....
in the mean  time i Placed a 

````
zeroconf:
  default_interface: true
````

and
it seems the the eror disapeared 


I will go on with card now... thanks a lot for your help

**Comment by boralyl** [comment]
Awesome, glad I was able to provide some assistance!
