### ISSUE TITLE
Trying to add the integration

### ISSUE THREAD

**Issue by TgMrP** [boralyl/kodi-recently-added#9]
I'm trying to add the integration but it's stuck...
![](https://user-images.githubusercontent.com/66732007/106221251-f58d1100-61e5-11eb-9921-db79f016e08d.png)

**Comment by boralyl** [comment]
Could you check the logs to see if there are any messages related to this component?  Don't have much to go off of with the screenshot, but if the component was causing an error you should find a message in the logs.

**Comment by TgMrP** [comment]
i get only warning
`You are using a custom integration for kodi_recently_added which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

I'll try to remove kodi integration and reinstall kodi-recently-added

Thanks for the quick reply

**Comment by TgMrP** [comment]
> Could you check the logs to see if there are any messages related to this component? Don't have much to go off of with the screenshot, but if the component was causing an error you should find a message in the logs.

Sorry, now it works ;)
How do i add
`hide_watched: true`
If the integration through the UI Integration
